### ISSUE TITLE
Can not spawn several getConnection

### ISSUE THREAD

**Issue by danielo515** [seriousManual/mockgo#20]
Hello,

I want to say that the following sentence 

> You can retrieve connections to as many databases as you wish. 

 is not true .
If you try to connect to two different databases you will get conflicts because mockgo will try to spawn to mongodb instances. While one may succeed, the second one will fail because the port is already in use or because a lockfile exists.
To workaround this I have moved all the database mockups to a single module , promisified the connections and check if a connection attempt is in course , and if it is then just return the same connection  promise. 
It would be very convenient to be able to spawn several databases without any conflict at all.

Regards

**Comment by seriousManual** [comment]
hi, thank you for your feedback, i think this issue will be adressed when the rewrite has been finished (see https://github.com/seriousManual/mockgo/issues/16#issuecomment-298168224)!

**Comment by seriousManual** [comment]
this should be resolved with v2, will be released to npm this evening (CET)!
please check if this works for you!
