### ISSUE TITLE
Missing return on line 63

### ISSUE THREAD

**Issue by danielo515** [seriousManual/mockgo#21]
I think your code is missing a return on the following line 

https://github.com/seriousManual/mockgo/blob/master/index.js#L63

This will cause very weird​ behaviors, like deleting cached instances and calling the callback twice, both with an error and with a null connection.

**Comment by seriousManual** [comment]
thank you for this issue and apologies for not reacting earlier, i somehow missed the issues on this project.

the bug you mentioned is fixed and release in 1.1.7
