### ISSUE TITLE
Update API to return Promise?

### ISSUE THREAD

**Issue by stevenguh** [seriousManual/mockgo#27]
Hi, it would be nice if we have the methods in the API return Promise if no callback is provided.

**Comment by seriousManual** [comment]
hi,
thanks for the suggestion, I'm currently working on the upgrade to the latest version of the underlying library which involves a complete rewrite of the api, i will keep this in mind!

**Comment by nikwen** [comment]
Please do this. :)

**Comment by seriousManual** [comment]
@DaniJG did an amazing job in rewriting most of the module adressing this issue, release is due for this evening (CET)!
