### ISSUE TITLE
Upgrade to latest mongodb-prebuilt so we can target mongo versions above 3.2

### ISSUE THREAD

**Issue by DaniJG** [seriousManual/mockgo#31]
Mockgo depends on mongodb-prebuilt 4.6 which ends up downloading mongo 3.2

This means your tests will break if you write code that targets features added in later versions of mongo like 3.4 or  3.6

Upgrading mockgo to depend on the latest mongodb-prebuilt (6.3) would allow us to keep using it while writing code that targets the latest mongo releases.

**Comment by seriousManual** [comment]
merged, release coming up!
thanks!
